import { type Node, parse } from "acorn";

type Ast = Node & { [key: string]: unknown };
type Value = string | number | boolean | null | Value[] | { [key: string]: Value };
export class UnsupportedNavigationError extends Error {
  readonly code = "UNSUPPORTED_NAVIGATION_FORMAT";
  constructor() {
    super(
      "Only static sidebar object/array literals are supported. Dynamic JavaScript and TypeScript are not executed.",
    );
  }
}
function literal(node: Ast): Value {
  if (node.type === "Literal" && ["string", "number", "boolean"].includes(typeof node.value))
    return node.value as Value;
  if (node.type === "Literal" && node.value === null) return null;
  if (node.type === "ArrayExpression")
    return (node.elements as Ast[]).map((n) => {
      if (!n) throw new UnsupportedNavigationError();
      return literal(n);
    });
  if (node.type === "ObjectExpression") {
    const result: Record<string, Value> = {};
    for (const prop of node.properties as Ast[]) {
      if (prop.type !== "Property" || prop.computed || prop.method || prop.kind !== "init")
        throw new UnsupportedNavigationError();
      const key = prop.key as Ast,
        name = key.type === "Identifier" ? String(key.name) : String(key.value);
      if (["__proto__", "prototype", "constructor"].includes(name) || Object.hasOwn(result, name))
        throw new UnsupportedNavigationError();
      result[name] = literal(prop.value as Ast);
    }
    return result;
  }
  throw new UnsupportedNavigationError();
}
export function parseNavigation(source: string) {
  let tree: Ast;
  try {
    tree = parse(source, { ecmaVersion: "latest", sourceType: "module" }) as unknown as Ast;
  } catch {
    throw new UnsupportedNavigationError();
  }
  const variables = new Map<string, Ast>();
  let selected: Ast | undefined;
  for (const statement of tree.body as Ast[]) {
    if (statement.type === "VariableDeclaration") {
      for (const decl of statement.declarations as Ast[]) {
        const id = decl.id as Ast;
        if (id.type !== "Identifier" || !decl.init) throw new UnsupportedNavigationError();
        variables.set(String(id.name), decl.init as Ast);
      }
    } else if (statement.type === "ExportDefaultDeclaration")
      selected = statement.declaration as Ast;
    else if (statement.type === "ExpressionStatement") {
      const expression = statement.expression as Ast,
        left = expression.left as Ast;
      if (
        expression.type !== "AssignmentExpression" ||
        expression.operator !== "=" ||
        left?.type !== "MemberExpression" ||
        left.computed ||
        (left.object as Ast).name !== "module" ||
        (left.property as Ast).name !== "exports"
      )
        throw new UnsupportedNavigationError();
      selected = expression.right as Ast;
    } else throw new UnsupportedNavigationError();
  }
  if (selected?.type === "Identifier") selected = variables.get(String(selected.name));
  if (!selected) throw new UnsupportedNavigationError();
  const value = literal(selected);
  if (
    !value ||
    Array.isArray(value) ||
    typeof value !== "object" ||
    Object.values(value).some((v) => !Array.isArray(v))
  )
    throw new UnsupportedNavigationError();
  return { value: value as Record<string, Value[]>, start: selected.start, end: selected.end };
}
export interface NavigationItem {
  id: string;
  label: string;
  document?: string;
  children?: NavigationItem[];
  editable: boolean;
}
export function navigationTree(value: Record<string, Value[]>): NavigationItem[] {
  const items = (list: Value[], base: string): NavigationItem[] =>
    list.map((item, index) => {
      const id = `${base}/${index}`;
      if (typeof item === "string") return { id, label: item, document: item, editable: true };
      if (item && !Array.isArray(item) && typeof item === "object")
        return {
          id,
          label: String(item.label ?? item.id ?? item.type ?? "item"),
          document: item.type === "doc" ? String(item.id) : undefined,
          editable: item.type !== "autogenerated",
          children: Array.isArray(item.items) ? items(item.items, `${id}/items`) : undefined,
        };
      return { id, label: "unsupported", editable: false };
    });
  return Object.entries(value).map(([name, list]) => ({
    id: name,
    label: name,
    editable: true,
    children: items(list, name),
  }));
}
export type NavigationPosition = number | "first" | "last" | { before: string } | { after: string };
export function editNavigation(
  source: string,
  input: {
    action: "add" | "move" | "remove";
    document?: string;
    item?: string;
    parent?: string;
    position?: NavigationPosition;
  },
) {
  if (
    input.action === "move" &&
    input.item &&
    (input.parent === input.item || input.parent?.startsWith(`${input.item}/`))
  )
    throw new Error("Navigation cycle");
  const parsed = parseNavigation(source),
    value = parsed.value;
  function locate(pointer: string): { list: Value[]; index: number } {
    const parts = pointer.split("/");
    const root = value[parts[0] ?? ""];
    if (!root || parts.length % 2 !== 0) throw new Error("Navigation item not found");
    let list: Value[] = root;
    for (let i = 1; i < parts.length - 1; i += 2) {
      const item: Value | undefined = list[Number(parts[i])];
      if (
        parts[i + 1] !== "items" ||
        !item ||
        typeof item !== "object" ||
        Array.isArray(item) ||
        !Array.isArray(item.items)
      )
        throw new Error("Navigation parent not found");
      list = item.items;
    }
    const index = Number(parts.at(-1));
    if (!Number.isInteger(index) || index < 0 || index >= list.length)
      throw new Error("Navigation item not found");
    return { list, index };
  }
  // Resolve destination before removing the source so sibling indices cannot shift it.
  let destination: Value[] | undefined;
  if (input.action !== "remove") {
    if (!input.parent) throw new Error("Navigation parent is required");
    destination = value[input.parent];
    if (!destination) {
      const found = locate(input.parent),
        parent = found.list[found.index];
      if (
        parent &&
        typeof parent === "object" &&
        !Array.isArray(parent) &&
        Array.isArray(parent.items)
      )
        destination = parent.items;
    }
    if (!destination) throw new Error("Navigation parent not found");
  }
  let anchor: { list: Value[]; index: number } | undefined;
  if (typeof input.position === "object")
    anchor = locate("before" in input.position ? input.position.before : input.position.after);
  if (anchor && anchor.list !== destination)
    throw new Error("Position anchor belongs to another parent");
  let item: Value = input.document ?? "";
  if (input.action !== "add") {
    if (!input.item) throw new Error("Navigation item is required");
    const found = locate(input.item);
    item = found.list[found.index] ?? null;
    if (item === null) throw new Error("Navigation item not found");
    if (
      input.action === "move" &&
      (input.parent === input.item || input.parent?.startsWith(`${input.item}/`))
    )
      throw new Error("Navigation cycle");
    if (anchor && anchor.list === found.list) {
      if (anchor.index === found.index)
        throw new Error("Cannot position an item relative to itself");
      if (found.index < anchor.index) anchor.index--;
    }
    found.list.splice(found.index, 1);
  } else if (!input.document) throw new Error("Document is required");
  if (destination) {
    const index = anchor
      ? anchor.index + (typeof input.position === "object" && "after" in input.position ? 1 : 0)
      : input.position === "first"
        ? 0
        : typeof input.position === "number"
          ? input.position
          : destination.length;
    if (!Number.isInteger(index) || index < 0 || index > destination.length)
      throw new Error("Invalid navigation position");
    destination.splice(index, 0, item);
  }
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  return (
    source.slice(0, parsed.start) +
    JSON.stringify(value, null, 2).replace(/\n/g, newline) +
    source.slice(parsed.end)
  );
}
