/** Synthetic, local-only UI fixture. Never contains customer repository content. */
import { createHash } from "node:crypto";
import {
  closeDatabase,
  encryptSecret,
  getDatabase,
  hashOpaqueToken,
  PushDocsRepository,
} from "../packages/db/src/index";

if (process.env.DATABASE_URL !== "postgres://pushdocs:pushdocs@localhost:55432/pushdocs")
  throw new Error("UI fixtures require the dedicated localhost:55432 database");
const store = new PushDocsRepository(getDatabase());
if (await store.isBootstrapped()) throw new Error("Seed only an empty database");
const user = await store.createOperator({
  displayName: "Анна Редактор",
  email: "anna@example.test",
  passwordHash: "no-password-login",
});
const connection = await store.createConnection({
  name: "GitLab · демонстрация",
  kind: "gitlab",
  baseUrl: "http://127.0.0.1:4555",
  secretEncrypted: encryptSecret("synthetic-demo"),
});
const config = JSON.stringify(
  {
    version: 1,
    templates: [
      {
        id: "article",
        label: "Статья с переводом",
        path: "docs/{slug}.mdx",
        content: "---\ntitle: {title}\n---\n",
        companions: [
          {
            path: "i18n/en/docusaurus-plugin-content-docs/current/{slug}.mdx",
            content: "# {title}\n",
          },
        ],
      },
    ],
  },
  null,
  2,
);
for (const [slug, name] of [
  ["knowledge", "База знаний"],
  ["independent", "Второй Docusaurus-проект"],
]) {
  const project = await store.createProject({
    connectionId: connection.id,
    defaultBranch: "main",
    name,
    operatorUserId: user.id,
    repositoryFullName: `demo/${slug}`,
    repositoryProviderId: slug,
    repositoryUrl: `http://127.0.0.1:4555/demo/${slug}.git`,
    rootPath: ".",
    slug,
  });
  const entries = [
    [
      "docs/introduction.mdx",
      "Начало работы",
      '---\ntitle: Начало работы\nsidebar_position: 1\n---\n\n# Добро пожаловать\n\nРедактируйте документацию, работайте с ветками и обсуждайте изменения в одном приложении.\n\n## Создайте первую статью\n\n1. Выберите рабочую ветку.\n2. Добавьте документ и изображения.\n3. Проверьте изменения перед отправкой.\n\n:::tip Совет\nСохранение черновика не создаёт коммит в Git.\n:::\n\n<Callout title="Обратите внимание" />\n',
    ],
    [
      "docs/guides/automation-and-segmentation/very-long-article-name-for-layout-testing.mdx",
      "Автоматизация и сегментация: подробное руководство для редактора",
      "# Автоматизация\n\nСценарии автоматизации и сегментации.",
    ],
    ["docs/guides/_category_.json", "Категория", '{"label":"Руководства","position":2}\n'],
    ["docs/guides/redirect.mdx", "Redirect", '<Redirect to="/docs/introduction" />'],
    [
      "i18n/en/docusaurus-plugin-content-docs/current/introduction.mdx",
      "Getting started",
      "# Getting started\n\nWelcome to the documentation.",
    ],
    [".pushdocs/config.json", "Настройки PushDocs", config],
    [
      "sidebars.js",
      "Навигация",
      "module.exports = { docs: [{type: 'autogenerated', dirName: '.'}] };\n",
    ],
  ];
  const documents = entries.map(([path, title, content]) => ({
    path,
    title,
    content,
    contentHash: createHash("sha256").update(content).digest("hex"),
    locale: path.startsWith("i18n") ? "en" : "default",
    version: "current",
  }));
  await store.replaceImportedDocuments(
    project.id,
    "main",
    "1234567890abcdef1234567890abcdef12345678",
    documents,
    documents.map((file) => file.path),
  );
  await store.ensureBranches(
    project.id,
    Array.from({ length: 130 }, (_, i) => ({
      name: `docs/article-${i + 1}`,
      sha: "1234567890abcdef1234567890abcdef12345678",
    })),
  );
  await store.ensureProjectComponents(project.id, ["Callout"]);
  await store.createComment({
    projectId: project.id,
    userId: user.id,
    branch: "main",
    documentPath: "docs/introduction.mdx",
    body: "Добавим пример с изображением перед отправкой на проверку.",
    anchorQuote: null,
  });
  console.log(`${name}: http://localhost:3000/projects/${project.id}/documents`);
}
await store.createSession(
  user.id,
  hashOpaqueToken("pushdocs-local-ui-session"),
  new Date(Date.now() + 86400000),
);
await closeDatabase();
